apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: typo3
    name: typo3
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: cloudwerkstatt
    creationTimestamp: null
    labels:
      app: typo3
    name: typo3-8.7.1lts
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: typo3:8.7.1lts
    postCommit: {}
    resources: {}
    source:
      contextDir: typo3/
      git:
        uri: https://github.com/nikelmark/typo3.git
      sourceSecret:
        name: "sshsecret"
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/rhscl/php-56-rhel7:latest
      type: Docker
    triggers:
    - github:
        secret: KKOWudRQA3e1kSSsqMq7
      type: GitHub
    - generic:
        secret: lqmXdvDbhio8Wj3S7Alw
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
